name: "Publish npm package"
author: "zb"
branding:
  icon: "anchor"
  color: "blue"
description: "public package"
inputs:
  tag:
    description: "tag"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
