name: "Publish npm package"
author: "zb"
branding:
  icon: "anchor"
  color: "blue"
description: "public package"
inputs:
  name:
    description: "name"
    required: false
  host:
    description: "host"
    required: false
  rea:
    description: "rea"
    required: false
  tag:
    description: "tag"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
