name: "Publish npm package"
author: "zb"
branding:
  icon: "anchor"
  color: "blue"
description: "public package"
inputs:
  token:
    description: "token"
    required: true
    default: ${{ github.token }}
runs:
  using: "docker"
  image: "Dockerfile"
