name: "Publish npm package Or Delete Tag"
author: "zb"
branding:
  icon: "anchor"
  color: "blue"
description: "public package"
inputs:
  repository:
    description: "仓库名称"
    default: ${{ github.repository }}
  token:
    description: "用户授权token"
    required: false
  tag:
    description: "标签"
    required: false
  delete:
    description: "是否是删除"
    default: false
runs:
  using: "docker"
  image: "Dockerfile"
